services:
  - type: web
    name: remoteorder-server
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: remoteorder-db
          property: connectionString
    autoDeploy: true

  - type: pserv
    name: remoteorder-db
    ipAllowList: []
    plan: free
    postgresVersion: 15
